routes/web.php
<?php

use App\Http\Controllers\Admin\Comment\CommentController as AdminCommentController;
use App\Http\Controllers\Admin\Item\ItemController as AdminItemController;
use App\Http\Controllers\Admin\Item\ItemMultiStepFormController as AdminItemMultiStepFormController;
use App\Http\Controllers\Admin\Item\TrashedItemController as AdminTrashedItemController;
use App\Http\Controllers\Admin\User\UserController as AdminUserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\User\Comment\CommentController;
use App\Http\Controllers\User\Equipment\EquipmentController;
use App\Http\Controllers\User\Item\ItemController as UserItemController;
use App\Http\Livewire\ItemListByTypes as UserItemListByTypes;
use App\Http\Livewire\ShoppingCart as UserShoppingCart;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::prefix('/admin')->name('admin.')->middleware(['auth', 'admin'])->group(function () {

    Route::prefix('/items')->name('items.')->group(function () {
        Route::get('/create-step-one', [AdminItemMultiStepFormController::class, 'createStepOne'])
            ->name('create.step.one');
        Route::post('/create-step-one', [AdminItemMultiStepFormController::class, 'postCreateStepOne'])
            ->name('create.step.one.post');
        Route::get('/create-step-two', [AdminItemMultiStepFormController::class, 'createStepTwo'])
            ->name('create.step.two');
        Route::post('/create-step-two', [AdminItemMultiStepFormController::class, 'postCreateStepTwo'])
            ->name('create.step.two.post');
        Route::get('/create-step-three', [AdminItemMultiStepFormController::class, 'createStepThree'])
            ->name('create.step.three');
        Route::post('/create-step-three', [AdminItemMultiStepFormController::class, 'postCreateStepThree'])
            ->name('create.step.three.post');
        Route::get('/create-cancel', [AdminItemMultiStepFormController::class, 'cancelCreateItem'])
            ->name('create.cancel');
    });

    Route::resource('/items', AdminItemController::class);

    Route::prefix('/trashed')->name('trashed.')->group(function () {
        Route::get('/', [AdminTrashedItemController::class, 'index'])->name('index');
        Route::get('/{item}', [AdminTrashedItemController::class, 'show'])->name('show')->withTrashed();
        Route::patch('/{item}', [AdminTrashedItemController::class, 'update'])->name('update')->withTrashed();
        Route::delete('/{item}', [AdminTrashedItemController::class, 'destroy'])->name('destroy')->withTrashed();
    });

    Route::prefix('/users')->name('users.')->group(function () {
        Route::get('/{user}/items', [AdminUserController::class, 'userLikedItems'])->name('liked.items');
        Route::get('/{user}/comments', [AdminUserController::class, 'userComments'])->name('comments');
    });

    Route::resource('/users', AdminUserController::class);

    Route::prefix('/comments')->name('comments.')->group(function () {
        Route::delete('/delete/{comment}', [AdminCommentController::class, 'delete'])->name('delete');
    });

});

Route::prefix('/user')->name('user.')->middleware('auth')->group(function () { // add middleware authenticated user

    Route::prefix('/items')->name('items.')->group(function () {
        Route::get('/', function () {
        return view('user.items.item-list');
        })->name('index');
        Route::get('/item-by-types', function () {
        return view('user.items.items-by-types');
        })->name('list-by-types');
//        Route::get('/item-by-types', UserItemListByTypes::class)->name('list-by-types');
        Route::get('/{item}', [UserItemController::class, 'show'])->name('show');
    });

    Route::get('/shopping-cart', function () {
    return view('user.items.shopping-cart');
    })->name('shopping-cart');
//    Route::get('/shopping-cart', UserShoppingCart::class)->name('shopping-cart');

    Route::prefix('/equipment')->name('equipment.')->group(function () {
        Route::get('/main', [EquipmentController::class, 'main'])->name('main');
        Route::get('/liked/items', [EquipmentController::class, 'likedItems'])->name('liked.items');
        Route::put('/like/{item}', [EquipmentController::class, 'likeItem'])->name('like.item');
        Route::get('/purchased/items', [EquipmentController::class, 'purchasedItems'])->name('purchased.items');
    });

    Route::prefix('/comment')->name('comment.')->group(function () {
        Route::get('/', [CommentController::class, 'index'])->name('index');
        Route::put('/store/{item}', [CommentController::class, 'store'])->name('store');
        Route::get('/{comment}', [CommentController::class, 'edit'])->name('edit');
        Route::patch('/update/{comment}', [CommentController::class, 'update'])->name('update');
        Route::delete('/delete/{comment}', [CommentController::class, 'delete'])->name('delete');
    });
});

require __DIR__.'/auth.php';

app/Http/Controllers/Admin/Item/ItemController.php
<?php

namespace App\Http\Controllers\Admin\Item;

use App\Http\Controllers\Controller;
use App\Models\Craft;
use App\Models\Item;
use App\Models\Type;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use function to_route;
use function view;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $items = Item::with('type')->latest('created_at')->paginate(15);

        return view('admin.items.index', compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.items.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|max:20',
            'description' => 'required|max:650',
        ]);

        Item::create([
            'uuid' => Str::uuid(),
            'title' => $request->title,
            'description' => $request->description,
            'type_id' => 1,
        ]);

        return to_route('admin.items.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Item $item)
    {
        $itemsForCraft = self::getItemsForCraft($item);

        return view('admin.items.show', compact('item', 'itemsForCraft'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Item $item)
    {
        $types = Type::all();
        $itemsForCraft = Item::all();
        $oldItemsForCraft = self::getItemsForCraft($item);
        $craftExist = ! empty($oldItemsForCraft);

        return view('admin.items.edit',
            compact('item', 'types', 'itemsForCraft', 'oldItemsForCraft', 'craftExist'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Item $item)
    {
        $data = $request->validate([
            'title' => 'required|max:20',
            'description' => 'required|max:650',
            'image' => ['nullable', 'image:jpg, jpeg, png'],
            'type_id' => 'required|not_in:-1',
        ]);

        if (isset($data['image'])) {
            $imageName = $request->file('image')->getClientOriginalName();
            $image_path = $request->file('image')->storeAs('items', $imageName);
            $data['image'] = '/storage/'.$image_path;
        }

        $craftRecipe = $request->validate([
            'position_1' => 'sometimes',
            'position_2' => 'sometimes',
            'position_3' => 'sometimes',
            'position_4' => 'sometimes',
            'position_5' => 'sometimes',
            'position_6' => 'sometimes',
            'position_7' => 'sometimes',
            'position_8' => 'sometimes',
            'position_9' => 'sometimes',
        ]);

        $newItemsForCraft = null;
        foreach ($craftRecipe as $position => $itemId) {
            if ($itemId != -1) {
                $newItemsForCraft[] = [
                    'item_for_crafting' => $itemId,
                    'position' => explode('_', $position)[1],
                ];
            }
        }

        if ($newItemsForCraft == null) {
            Craft::where('item_id', $item->id)->delete();
        } else {
            Craft::where('item_id', $item->id)->delete();
            $item->crafts()->createMany($newItemsForCraft);
        }

        $item->update($data);

        return to_route('admin.items.show', $item)->with('success', ' Item update successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Item $item)
    {
        $item->delete();

        return to_route('admin.items.index')->with('success', ' Item moved to trash');
    }

    protected function getItemsForCraft(Item $item)
    {
        $itemsForCraft = [];

        foreach ($item->crafts()->get() as $craftItem) {
            $itemsForCraft[$craftItem->position] = Item::where('id', $craftItem->item_for_crafting)->firstOrFail();
        }

        return $itemsForCraft;
    }
}

app/Http/Controllers/Admin/Item/ItemMultiStepFormController.php
<?php

namespace App\Http\Controllers\Admin\Item;

use App\Http\Controllers\Controller;
use App\Models\Item;
use App\Models\Type;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use function redirect;
use function view;

class ItemMultiStepFormController extends Controller
{
//-----------------Step One---------------------------------------------------------------------------------------------
    public function createStepOne(Request $request)
    {
        $item = $request->session()->get('item');
        $craftExist = $request->session()->get('craftExist');
//        $craft = new Craft() -------------------------------------------rewrite code to use in session craft model ???
        $types = Type::all();

        return view('admin.items.create-step-one', compact('item'))
            ->with('types', $types)
            ->with('craftExist', $craftExist);
    }

    public function postCreateStepOne(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required|max:20',
            'description' => 'required|max:650',
            'type_id' => 'required|not_in:-1',
        ]);

        if (empty($request->session()->get('item'))) {
            $item = new Item();
            $item->fill($validatedData);
            $request->session()->put('item', $item);
        } else {
            $item = $request->session()->get('item');
            $item->fill($validatedData);
            $request->session()->put('item', $item);
        }

        if ($request->input('craftExist')) {
            $request->session()->put('craftExist', true);

            return redirect()->route('admin.items.create.step.two');

        } else {
            $request->session()->put('craftExist', false);
            $request->session()->forget('itemsForCraft');

            return redirect()->route('admin.items.create.step.three');
        }
    }

//-----------------Step Two---------------------------------------------------------------------------------------------
    public function createStepTwo(Request $request)
    {
        $item = $request->session()->get('item');
        $itemsForCraft = Item::all();
        $types = Type::all();

        $oldItemsForCraft = $request->session()->get('itemsForCraft');

        return view('admin.items.create-step-two', compact('item'))
            ->with('itemsForCraft', $itemsForCraft)
            ->with('types', $types)
            ->with('oldItemsForCraft', $oldItemsForCraft);
    }

    public function postCreateStepTwo(Request $request)
    {
        $craftRecipe = $request->validate([
            'position_1' => 'sometimes',
            'position_2' => 'sometimes',
            'position_3' => 'sometimes',
            'position_4' => 'sometimes',
            'position_5' => 'sometimes',
            'position_6' => 'sometimes',
            'position_7' => 'sometimes',
            'position_8' => 'sometimes',
            'position_9' => 'sometimes',
        ]);

        $itemsForCraft = null;
        foreach ($craftRecipe as $position => $itemId) {
            if ($itemId != -1) {
                $itemsForCraft[explode('_', $position)[1]] = $itemId;
            }
        }

        if ($itemsForCraft == null) {
            return redirect()->route('admin.items.create.step.two')
                ->with('warning',
                    'There must be crafting for this item.
                    If not, go back to the previous page and remove the checkbox for the crafting recipe');
        }

        $request->session()->put('itemsForCraft', $itemsForCraft);

        return redirect()->route('admin.items.create.step.three');
    }

//-----------------Step Three-------------------------------------------------------------------------------------------
    public function createStepThree(Request $request)
    {
        $item = $request->session()->get('item');
        $craftExist = $request->session()->get('craftExist');

        return view('admin.items.create-step-three', compact('item'))->with('craftExist', $craftExist);
    }

    public function postCreateStepThree(Request $request)
    {
        $request->validate([
            'image' => ['required', 'image:jpg, jpeg, png'],
        ]);
        $imageName = $request->file('image')->getClientOriginalName();
        $image_path = $request->file('image')->storeAs('items', $imageName);

        $item = $request->session()->get('item');

        $item->uuid = Str::uuid();
        $item->image = '/storage/'.$image_path;

        $item->save();

        if ($request->session()->get('craftExist')) {
            $craft = $request->session()->get('itemsForCraft');
            $craftForInsert = [];
            foreach ($craft as $position => $itemForCraftId) {
                $craftForInsert[] = [
                    'item_for_crafting' => $itemForCraftId,
                    'position' => $position,
                ];
            }
            $item->crafts()->createMany($craftForInsert);
            $request->session()->forget('itemsForCraft');
        }

        $request->session()->forget('item');
        $request->session()->forget('craftExist');

        return redirect()->route('admin.items.index');
    }

//-----------------Cancel Item Creation---------------------------------------------------------------------------------
    public function cancelCreateItem(Request $request)
    {
        $request->session()->forget('item');
        $request->session()->forget('itemsForCraft');
        $request->session()->forget('craftExist');

        return redirect()->route('admin.items.index');
    }
}

app/Http/Controllers/Admin/Item/TrashedItemController.php
<?php

namespace App\Http\Controllers\Admin\Item;

use App\Http\Controllers\Controller;
use App\Models\Item;
use function to_route;
use function view;

class TrashedItemController extends Controller
{
    public function index()
    {
        $items = Item::with('type')->onlyTrashed()->paginate(10);

        return view('admin.trashedItems.index', ['items' => $items]);
    }

    public function show(Item $item)
    {

        $itemsForCraft = self::getItemsForCraft($item);

        return view('admin.trashedItems.show', compact('item', 'itemsForCraft'));
    }

    public function update(Item $item)
    {
        $item->restore();

        return to_route('admin.items.show', $item)->with('success', 'Item restore');
    }

    public function destroy(Item $item)
    {
        $item->forceDelete();

        return to_route('admin.trashed.index')->with('success', 'Item deleted forever');
    }

    protected function getItemsForCraft(Item $item)
    {
        $itemsForCraft = [];

        foreach ($item->crafts()->get() as $craftItem) {
            $itemsForCraft[$craftItem->position] = Item::where('id', $craftItem->item_for_crafting)->firstOrFail();
        }

        return $itemsForCraft;
    }
}

app/Http/Controllers/User/Equipment/EquipmentController.php
<?php

namespace App\Http\Controllers\User\Equipment;

use App\Http\Controllers\Controller;
use App\Models\Item;

class EquipmentController extends Controller
{
    public function main()
    {
        $totalLikedItems = auth()->user()->likedItems()->count();
        $totalComments = auth()->user()->comments()->count();

        return view('user.equipment.main', compact('totalLikedItems', 'totalComments'));
    }

    public function likedItems()
    {
        $items = auth()->user()->likedItems;

        return view('user.equipment.liked-items', compact('items'));
    }

    public function likeItem(Item $item)
    {
        auth()->user()->likedItems()->toggle($item->id); // "toggle" add the ability to attach and detach an item

        return redirect()->back();
    }

    public function purchasedItems()
    {
        $items = auth()->user()->purchasedItems;

        return view('user.equipment.purchased-items', compact('items'));
    }
}

resources/views/user/items/index.blade.php
@extends('user.layouts.app')

@section('header')
    {{ __('Items') }}
@endsection

@section('content')
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            <x-alert-success>
                {{ session('success') }}
            </x-alert-success>

            <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg mt-4">
                <div class="row row-cols-1 row-cols-md-5 g-4">

                    @foreach($items as $item)

                        <div class="col">
                            <div class="card rounded-top">
                                <img src="{{ asset($item->image) }}" class="card-img-top p-4" alt="{{ $item->title }}">
                                <div class="card-body text-center ">
                                    <a href="{{ route('user.items.show', $item->id) }}" class="card-title fs-4 fw-medium fw-bolder stretched-link">{{ $item->title }}</a>
                                </div>
                            </div>
                        </div>
                    @endforeach

                </div>
            </div>

            <div class="mt-3">
                {{ $items->links() }}
            </div>
        </div>
    </div>
@endsection

resources/views/user/items/item-list.blade.php
@extends('user.layouts.app')

@section('header')
    {{__('Items List')}}
@endsection

@section('content')
    <livewire:item-list/>
@endsection

resources/views/user/items/items-by-types.blade.php
@extends('user.layouts.app')

@section('header')
    {{ __('Items by types') }}
@endsection

@section('content')

    <livewire:item-list-by-types/>
{{--    <div class="py-12">--}}
{{--        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">--}}

{{--            <x-alert-success>--}}
{{--                {{ session('success') }}--}}
{{--            </x-alert-success>--}}

{{--            <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg mt-4">--}}
{{--                <div class="container px-4 py-5">--}}

{{--                        <div class="col-sm-8 py-5 mx-auto">--}}
{{--                            <p>craft</p>--}}
{{--                        </div>--}}

{{--                    <div class="row">--}}
{{--                        @foreach($types as $type)--}}
{{--                            <div class="col">--}}
{{--                                <h1 class="fs-3 mb-2">{{ $type->title }}</h1>--}}

{{--                                <ul class="list-group list-group-horizontal-sm">--}}
{{--                                    @foreach($type->items as $item)--}}
{{--                                        <li class="me-1 mb-1">--}}
{{--                                            <img src="{{ asset($item->image) }}"--}}
{{--                                                 class="card p-1" style="max-width: 70px"--}}
{{--                                                 alt="{{ $item->title }}">--}}
{{--                                        </li>--}}
{{--                                    @if($loop->iteration % 6 ==0 )--}}
{{--                                        </ul>--}}
{{--                                        <ul class="list-group list-group-horizontal-sm">--}}
{{--                                    @endif--}}

{{--                                    @endforeach--}}
{{--                                </ul>--}}
{{--                            </div>--}}
{{--                            @if($loop->iteration % 2 ==0 )--}}
{{--                                </div>--}}
{{--                                <div class="p-4"></div>--}}
{{--                                <div class="row">--}}
{{--                            @endif--}}
{{--                        @endforeach--}}
{{--                    </div>--}}


{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}

@endsection

resources/views/user/items/shopping-cart.blade.php
@extends('user.layouts.app')

@section('header')
    {{__('Cart')}}
@endsection

@section('content')

    <livewire:shopping-cart/>
@endsection

resources/views/user/items/show.blade.php
@extends('user.layouts.app')

@section('header')
    {{__('Items')}}
@endsection

@section('content')
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            <x-alert-success>
                {{ session('success') }}
            </x-alert-success>

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item link-primary link-offset-2">
                        <a href="{{ route('user.items.index') }}">Items</a>
                    </li>
                    <li class="breadcrumb-item" aria-current="page">
                        {{ $item->title }}
                    </li>
                </ol>
            </nav>

            <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg mt-4">

                <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2  border-bottom">

                    <div class="d-flex justify-between">
                        <h2 class="font-bold text-4xl ">
                            {{ $item->title }}
                        </h2>
                        @auth()
                            <form action="{{ route('user.equipment.like.item', $item) }}" method="post"
                                  class="ms-2">
                                @method('put')
                                @csrf
                                <button type="submit">
                                    @if(auth()->user()->likedItems->contains($item->id))
                                        <i class="bi bi-heart-fill fw-semibold">{{ $item->likedUsers->count() }}</i>
                                    @else
                                        <i class="bi bi-heart fw-semibold">{{ $item->likedUsers->count() }}</i>
                                    @endif
                                </button>
                            </form>
                        @endauth
                    </div>

                    <div class="btn-toolbar mb-2 mb-md-0">
                        <div class="btn-group me-2">
                            <!-- Text on left side of item title  -->
                        </div>
                    </div>
                </div>

                <div class="row row-cols-1 row-cols-md-2 align-items-start g-5 py-5">

                    <!-- Item main information -->
                    <div class="col d-flex flex-column align-items-start gap-2">
                        <img src="{{ asset($item->image) }}" alt="empty_section" width="150" height="150">
                        <p class="mt-2">
                            <b>Type:</b> {{ $item->type->title }}
                        </p>
                        <p class="mt-6" style="text-align: justify; width: 80%">
                            <b>Description:</b> {{ $item->description }}
                        </p>
                    </div>

                    <!-- Item craft  -->
                    <div class="col">
                        <div class="d-flex justify-content-center">
                            @if(!empty($itemsForCraft))
                                <table class="">
                                    <tr>
                                        @for($craftPosition = 1; $craftPosition < 10; $craftPosition++)
                                            <td class="border border-4 border-dark"  background="{{ asset('/storage/items/empty_section.jpg') }}">
                                                <div class="border border-3">
                                                    @if(isset($itemsForCraft[$craftPosition]))
                                                        <img src="{{ asset($itemsForCraft[$craftPosition]->image) }}"
                                                             alt="{{ $itemsForCraft[$craftPosition]->title }}"
                                                             width="80"
                                                             height="80">
                                                    @else
                                                        <img src="{{ asset('/storage/items/empty_section.jpg') }}"
                                                             alt="empty_section"
                                                             width="80"
                                                             height="80">
                                                    @endif
                                                </div>
                                            </td>

                                            @if($craftPosition % 3 == 0)
                                    </tr>
                                    <tr>
                                        @endif
                                        @endfor
                                    </tr>
                                </table>
                            @endif
                        </div>
                    </div>
                </div>
            </div>

            <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg mt-4">
                @auth
                    <!-- Form for new comment -->
                    <form action="{{ route('user.comment.store', $item) }}" class="w-50 " method="post"
                          enctype="multipart/form-data">
                        @method('put')
                        @csrf
                        <x-textarea
                            name="comment"
                            rows="3"
                            field="comment"
                            placeholder="Leave a comment"
                            class="w-full mt-6"
                            :value="@old('comment')">
                        </x-textarea>

                        <x-button class="mt-2">Save a comment</x-button>
                    </form>
                @endauth

                @if(count($item->comments) != 0)
                    <table class="table table-hover mt-6">
                        <thead>
                        <tr>
                            <th>Comments</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach($item->comments as $comment)
                            <tr>
                                <td class="align-middle w-75" style="text-align: justify">{{ $comment->message }}</td>
                                <td class="align-middle text-body-secondary ">
                                    <small class="text-body-secondary fw-semibold">{{ $comment->updated_at->diffForHumans() }}</small>
                                </td>
                                <td class="align-middle">
                                    <div class="d-flex align-items-center">
                                        @if(auth()->id() == $comment->user_id)
                                            <form action="{{ route('user.comment.delete', $comment) }}" method="post">

                                                <a href="{{ route('user.comment.edit', $comment) }}" class="btn btn-outline-primary text-gray-700">Edit</a>
                                                <input type="hidden" name="item_id" value="{{ $item->id }}">
                                                @method('delete')
                                                @csrf

                                                <button type="submit" class="btn btn-outline-danger text-gray-700"
                                                        onclick="return confirm('Are you sure you wish to delete your comment ?')">
                                                    Delete
                                                </button>
                                            </form>
                                        @endif
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                @endif

            </div>
        </div>
    </div>
@endsection