routes/web.php
<?php

use App\Http\Controllers\Admin\Comment\CommentController as AdminCommentController;
use App\Http\Controllers\Admin\Item\ItemController as AdminItemController;
use App\Http\Controllers\Admin\Item\ItemMultiStepFormController as AdminItemMultiStepFormController;
use App\Http\Controllers\Admin\Item\TrashedItemController as AdminTrashedItemController;
use App\Http\Controllers\Admin\User\UserController as AdminUserController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\User\Comment\CommentController;
use App\Http\Controllers\User\Equipment\EquipmentController;
use App\Http\Controllers\User\Item\ItemController as UserItemController;
use App\Http\Livewire\ItemListByTypes as UserItemListByTypes;
use App\Http\Livewire\ShoppingCart as UserShoppingCart;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::middleware('auth')->group(function () {
    Route::get('/profile', [ProfileController::class, 'edit'])->name('profile.edit');
    Route::patch('/profile', [ProfileController::class, 'update'])->name('profile.update');
    Route::delete('/profile', [ProfileController::class, 'destroy'])->name('profile.destroy');
});

Route::prefix('/admin')->name('admin.')->middleware(['auth', 'admin'])->group(function () {

    Route::prefix('/items')->name('items.')->group(function () {
        Route::get('/create-step-one', [AdminItemMultiStepFormController::class, 'createStepOne'])
            ->name('create.step.one');
        Route::post('/create-step-one', [AdminItemMultiStepFormController::class, 'postCreateStepOne'])
            ->name('create.step.one.post');
        Route::get('/create-step-two', [AdminItemMultiStepFormController::class, 'createStepTwo'])
            ->name('create.step.two');
        Route::post('/create-step-two', [AdminItemMultiStepFormController::class, 'postCreateStepTwo'])
            ->name('create.step.two.post');
        Route::get('/create-step-three', [AdminItemMultiStepFormController::class, 'createStepThree'])
            ->name('create.step.three');
        Route::post('/create-step-three', [AdminItemMultiStepFormController::class, 'postCreateStepThree'])
            ->name('create.step.three.post');
        Route::get('/create-cancel', [AdminItemMultiStepFormController::class, 'cancelCreateItem'])
            ->name('create.cancel');
    });

    Route::resource('/items', AdminItemController::class);

    Route::prefix('/trashed')->name('trashed.')->group(function () {
        Route::get('/', [AdminTrashedItemController::class, 'index'])->name('index');
        Route::get('/{item}', [AdminTrashedItemController::class, 'show'])->name('show')->withTrashed();
        Route::patch('/{item}', [AdminTrashedItemController::class, 'update'])->name('update')->withTrashed();
        Route::delete('/{item}', [AdminTrashedItemController::class, 'destroy'])->name('destroy')->withTrashed();
    });

    Route::prefix('/users')->name('users.')->group(function () {
        Route::get('/{user}/items', [AdminUserController::class, 'userLikedItems'])->name('liked.items');
        Route::get('/{user}/comments', [AdminUserController::class, 'userComments'])->name('comments');
    });

    Route::resource('/users', AdminUserController::class);

    Route::prefix('/comments')->name('comments.')->group(function () {
        Route::delete('/delete/{comment}', [AdminCommentController::class, 'delete'])->name('delete');
    });

});

Route::prefix('/user')->name('user.')->middleware('auth')->group(function () { // add middleware authenticated user

    Route::prefix('/items')->name('items.')->group(function () {
        Route::get('/', function () {
        return view('user.items.item-list');
        })->name('index');
        Route::get('/item-by-types', function () {
        return view('user.items.items-by-types');
        })->name('list-by-types');
//        Route::get('/item-by-types', UserItemListByTypes::class)->name('list-by-types');
        Route::get('/{item}', [UserItemController::class, 'show'])->name('show');
    });

    Route::get('/shopping-cart', function () {
    return view('user.items.shopping-cart');
    })->name('shopping-cart');
//    Route::get('/shopping-cart', UserShoppingCart::class)->name('shopping-cart');

    Route::prefix('/equipment')->name('equipment.')->group(function () {
        Route::get('/main', [EquipmentController::class, 'main'])->name('main');
        Route::get('/liked/items', [EquipmentController::class, 'likedItems'])->name('liked.items');
        Route::put('/like/{item}', [EquipmentController::class, 'likeItem'])->name('like.item');
        Route::get('/purchased/items', [EquipmentController::class, 'purchasedItems'])->name('purchased.items');
    });

    Route::prefix('/comment')->name('comment.')->group(function () {
        Route::get('/', [CommentController::class, 'index'])->name('index');
        Route::put('/store/{item}', [CommentController::class, 'store'])->name('store');
        Route::get('/{comment}', [CommentController::class, 'edit'])->name('edit');
        Route::patch('/update/{comment}', [CommentController::class, 'update'])->name('update');
        Route::delete('/delete/{comment}', [CommentController::class, 'delete'])->name('delete');
    });
});

require __DIR__.'/auth.php';

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    const ROLE_ADMIN = 0;

    const ROLE_READER = 1;

    public static function getRoles()
    {
        return [
            self::ROLE_ADMIN => 'admin',
            self::ROLE_READER => 'reader',
        ];
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'role',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function likedItems()
    {
        return $this->belongsToMany(Item::class, 'user_item_liked', 'user_id', 'item_id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class, 'user_id', 'id');
    }

    public function resource()
    {
        return $this->hasOne(UserResource::class);
    }

    public function purchasedItems()
    {
        return $this->belongsToMany(Item::class, 'user_item_purchased', 'user_id', 'item_id');
    }
}

app/Http/Controllers/Admin/User/UserController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Http\Controllers\Controller;
use App\Mail\User\PasswordMail;
use App\Models\User;
use Illuminate\Auth\Events\Registered;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Str;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $users = User::all();
        $roles = User::getRoles();

        return view('admin.users.index', compact('users', 'roles'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $roles = User::getRoles();

        return view('admin.users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = $request->validate([
            'name' => 'required|max:20',
            'email' => 'required|max:30|email|unique:users',
            'role' => 'required|integer',
        ]);

        $password = Str::random(10);
        $data['password'] = Hash::make($password);

        $user = User::firstOrCreate(['email' => $data['email']], $data);
//        Mail::to($data['email'])->send(new PasswordMail($password));

//        event(new Registered($user));

        return to_route('admin.users.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $user = User::where('id', $id)->firstOrFail();
        $totalLikedItems = $user->likedItems()->count();
        $totalComments = $user->comments()->count();

        return view('admin.users.show', compact('user', 'totalLikedItems', 'totalComments'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $user = User::where('id', $id)->firstOrFail();
        $roles = User::getRoles();

        return view('admin.users.edit', compact('user', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, User $user)
    {
        $data = $request->validate([
            'name' => 'required|max:20',
            'email' => 'required|max:30|email|unique:users,email,'.$request->user_id,
            'user_id' => 'required|integer|exists:users,id',
            'role' => 'required|integer|not_in:-1',
        ]);

        $user->update($data);

        return to_route('admin.users.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $user = User::where('id', $id)->firstOrFail();
        $user->delete();

        return to_route('admin.users.index')->with('success', ' Item moved to trash');
    }

    public function userLikedItems(User $user)
    {
        $items = $user->likedItems;

        return view('admin.users.liked-items', compact('user', 'items'));
    }

    public function userComments(User $user)
    {
        $comments = $user->comments;

        return view('admin.users.user-comments', compact('user', 'comments'));
    }
}

app/Http/Controllers/Api/User/ItemController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\ItemStoreRequest;
use App\Http\Resources\ItemCollection;
use App\Http\Resources\ItemResource;
use App\Models\Item;
use Illuminate\Http\Response;
use function response;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
//        return response()->json(new ItemCollection(Item::with('comments')->with('type')->paginate(3)), Response::HTTP_OK);
        return new ItemCollection(Item::with('type')->paginate(15));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(ItemStoreRequest $request)
    {
        $item = Item::create($request->validated());

        return new ItemResource($item);
    }

    /**
     * Display the specified resource.
     */
    public function show(Item $item)
    {
        return new ItemResource(Item::with('comments')->findOrFail($item->id));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(ItemStoreRequest $request, Item $item)
    {
        $item->update($request->validated());

        return new ItemResource($item);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Item $item)
    {
        $item->forceDelete();

        return response()->json(null, Response::HTTP_I_AM_A_TEAPOT);
    }
}

app/Http/Controllers/User/Comment/CommentController.php
<?php

namespace App\Http\Controllers\User\Comment;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use App\Models\Item;
use function auth;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use function redirect;
use function view;

class CommentController extends Controller
{
    public function index()
    {
        $comments = auth()->user()->comments;

        return view('user.comments.index', compact('comments'));
    }

    public function store(Request $request, Item $item)
    {
        $request->validate([
            'comment' => 'required|min:10',
        ]);

        $comment = new Comment();
        $comment->user_id = Auth::id();
        $comment->message = $request->comment;

        $item->comments()->save($comment);

        return redirect()->route('user.items.show', $item->id)
            ->with('success', 'Thank for your comment');
    }

    public function edit(Comment $comment, Item $item)
    {
        return view('user.comments.edit', compact('comment', 'item'));
    }

    public function update(Request $request, Comment $comment)
    {
        $data = $request->validate([
            'message' => 'required',
        ]);

        $comment->update($data);

        return redirect()->route('user.items.show', $comment->item_id)
            ->with('success', 'Your comment has been updated');
    }

    public function delete(Request $request, Comment $comment)
    {
        $comment->delete();

        return redirect()->route('user.items.show', $request->item_id)
            ->with('success', 'Your comment has been deleted');
    }
}

app/Http/Controllers/User/Equipment/EquipmentController.php
<?php

namespace App\Http\Controllers\User\Equipment;

use App\Http\Controllers\Controller;
use App\Models\Item;

class EquipmentController extends Controller
{
    public function main()
    {
        $totalLikedItems = auth()->user()->likedItems()->count();
        $totalComments = auth()->user()->comments()->count();

        return view('user.equipment.main', compact('totalLikedItems', 'totalComments'));
    }

    public function likedItems()
    {
        $items = auth()->user()->likedItems;

        return view('user.equipment.liked-items', compact('items'));
    }

    public function likeItem(Item $item)
    {
        auth()->user()->likedItems()->toggle($item->id); // "toggle" add the ability to attach and detach an item

        return redirect()->back();
    }

    public function purchasedItems()
    {
        $items = auth()->user()->purchasedItems;

        return view('user.equipment.purchased-items', compact('items'));
    }
}

app/Http/Controllers/User/Item/ItemController.php
<?php

namespace App\Http\Controllers\User\Item;

use App\Http\Controllers\Controller;
use App\Models\Item;
use Livewire\WithPagination;

class ItemController extends Controller
{
    use WithPagination;

    public function index()
    {
//        $equippedItems = Item::withCount('likedUsers')->orderBy('equipped_users_count', 'DESC')->get()->take(2); // return items with a count of how many users take it to equipment
        $items = Item::latest('created_at')->paginate(15);

        return view('user.items.index', compact('items'));
    }

    public function show(Item $item)
    {
//        $relatedItems = Item::where('type_id', $item->type_id)
//            ->where('id', '!=', $item->id)
//            ->get()
//            ->take(3);

        $itemsForCraft = self::getItemsForCraft($item);

        return view('user.items.show', compact('item', 'itemsForCraft'));
    }

    public function getItemsForCraft(Item $item)
    {
        $itemsForCraft = [];

        foreach ($item->crafts()->get() as $craftItem) {
            $itemsForCraft[$craftItem->position] = Item::where('id', $craftItem->item_for_crafting)->firstOrFail();
        }

        return $itemsForCraft;
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.app')

@section('header')
    {{ __('Create New User') }}
@endsection

@section('content')
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg">

                <form action="{{ route('admin.users.store') }}" method="post" class="w-50">
                    @csrf
                    <x-input
                        type="text"
                        name="name"
                        field="name"
                        placeholder="Name"
                        class="w-full"
                        autocomplete="off"
                        :value="@old('name')">
                    </x-input>

                    <x-input
                        type="text"
                        name="email"
                        field="email"
                        placeholder="Email"
                        class="w-full mt-2"
                        autocomplete="off"
                        :value="@old('email')">
                    </x-input>

                    <select class="rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 w-full mt-2"
                            name="role"
                            aria-label="Default select example">
                        @foreach($roles as $id => $role)
                                <option value="{{ $id }}" {{ $id == old('role') ? 'selected' : '' }}>{{ $role }}</option>
                        @endforeach
                    </select>

                    @error('role')
                    <div class="text-red-600 text-sm">{{ $message }}</div>
                    @enderror

                    <x-button class="mt-6">Save User</x-button>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('header')
    {{ __('Edit Item') }}
@endsection

@section('content')
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            <x-alert-success>
                {{ session('success') }}
            </x-alert-success>

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item link-primary link-offset-2">
                        <a href="{{ route('admin.users.index') }}">All users</a>
                    </li>
                    <li class="breadcrumb-item" aria-current="page">{{ $user->name }}</li>
                </ol>
            </nav>

            <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg">

                <form action="{{ route('admin.users.update', $user) }}" class="w-50" method="post" enctype="multipart/form-data">
                    @method('put')
                    @csrf
                    <x-input
                        type="text"
                        name="name"
                        field="name"
                        placeholder="Name"
                        class="w-full"
                        autocomplete="off"
                        :value="@old('name', $user->name )">
                    </x-input>

                    <select class="rounded-md shadow-sm border-gray-300 focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 w-full mt-2"
                            name="role"
                            aria-label="Default select example">
                        @foreach($roles as $id => $role)
                            <option value="{{ $id }}" {{ $id == $user->role || $id == old('role')  ? 'selected' : '' }}>{{ $role }}</option>
                        @endforeach
                    </select>

                    @error('role')
                    <div class="text-red-600 text-sm">{{ $message }}</div>
                    @enderror


                    <x-input
                        type="text"
                        name="email"
                        field="email"
                        placeholder="Email"
                        class="w-full mt-2"
                        autocomplete="off"
                        :value="@old('email', $user->email )">
                    </x-input>

                    <input type="hidden" name="user_id" value="{{ $user->id }}">
                    <x-button class="mt-6">Save User</x-button>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')

@section('header')
    {{ ('Users') }}
@endsection

@section('content')
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            <x-alert-success>
                {{ session('success') }}
            </x-alert-success>


            <a href="{{ route('admin.users.create') }}" class="btn btn-primary">+ New User</a>
            <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg mt-4 w-75">

                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Role</th>
                        <th class="text-center">Action</th>

                    </tr>
                    </thead>

                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td class="align-middle">{{ $user->id }}</td>
                            <td class="align-middle">{{ $user->name }}</td>
                            <td class="align-middle">{{ $user->email }}</td>
                            <td class="align-middle">{{ isset($user->role) ? $roles[$user->role] : 'default'}}</td>
                            <td class="text-center">
                                <form action="{{ route('admin.users.destroy', $user->id) }}" method="post">

                                    <a class="btn btn-outline-primary text-gray-700"
                                       href="{{ route('admin.users.show', $user->id) }}">See user</a>
                                    <a class="btn btn-outline-primary text-gray-700"
                                       href="{{ route('admin.users.edit', $user->id) }}">Edit</a>
                                    @method('delete')
                                    @csrf
                                    <button type="submit" class="btn btn-outline-danger text-gray-700"
                                            onclick="return confirm('Are you sure you wish to delete this user forever !?')">
                                        Delete
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach

                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/liked-items.blade.php
@extends('admin.layouts.app')

@section('header')
    {{ __('Liked Items') }}
@endsection

@section('content')
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            <x-alert-success>
                {{ session('success') }}
            </x-alert-success>

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item link-primary link-offset-2">
                        <a href="{{ route('admin.users.show', $user->id) }}">{{ $user->name }}</a>
                    </li>
                    <li class="breadcrumb-item" aria-current="page">Liked items</li>
                </ol>
            </nav>

            <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg mt-4">
                <div class="row row-cols-1 row-cols-md-5 g-4">


                    @if(count($items) != 0)
                        <table class="table table-hover w-50">
                            <thead>
                            <tr>
                                <th>Title</th>
                                <th></th>
                            </tr>
                            </thead>

                            <tbody>
                            @foreach($items as $item)
                                <tr>
                                    <td class="align-middle">
                                        <a href="{{ route('admin.items.show', $item) }}">{{ $item->title }}</a>
                                    </td>
                                    <td class="text-center">
                                        <i class="bi bi-heart-fill"></i>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    @else
                        <p class="fs-5">This user haven't any liked items</p>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/show.blade.php
@extends('admin.layouts.app')

@section('header')
    {{ __('Edit Item') }}
@endsection

@section('content')
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            <x-alert-success>
                {{ session('success') }}
            </x-alert-success>
            <div class="d-flex justify-content-between">

                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item link-primary link-offset-2">
                            <a href="{{ route('admin.users.index') }}">All users</a>
                        </li>
                        <li class="breadcrumb-item" aria-current="page">{{ $user->name }}</li>
                    </ol>
                </nav>

                <a class="btn btn-outline-primary text-gray-700"
                   href="{{ route('admin.users.edit', $user->id) }}">Edit {{ $user->name }}</a>
            </div>

            <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg mt-4">
                <div class="container px-4 py-5">
                    <h2 class="pb-2 border-bottom">{{ $user->name }}</h2>

                    <div class="row row-cols-1 row-cols-md-2 align-items-start g-5 py-5">
                        <div class="col d-flex flex-column align-items-start gap-2">
                            <h3 class="fw-bold">Future</h3>
                            <p class="text-body-secondary">Functional</p>
                            <button type="button" class="btn btn-primary" disabled>To be continue...</button>
                        </div>

                        <div class="col">
                            <div class="row row-cols-1 row-cols-md-2 g-4">

                                <div class="col">
                                    <div class="card text-bg-light mb-3" style="max-width: 18rem;">
                                        <div class="card-header">User liked items</div>
                                        <div class="card-body">
                                            <h5 class="card-title">Total: {{ $totalLikedItems }}</h5>
                                            <a href="{{ route('admin.users.liked.items', $user) }}" class="btn btn-outline-secondary text-gray-700">Vew all</a>
                                        </div>
                                    </div>
                                </div>

                                <div class="col">
                                    <div class="card border-success mb-3" style="max-width: 18rem;">
                                        <div class="card-header">All user comments</div>
                                        <div class="card-body">
                                            <h5 class="card-title">Total: {{ $totalComments }}</h5>
                                            <a href="{{ route('admin.users.comments', $user) }}" class="btn btn-outline-success text-gray-700">Vew all</a>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/user-comments.blade.php
@extends('admin.layouts.app')

@section('header')
    {{ __('Equipment') }}
@endsection

@section('content')
    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">

            <x-alert-success>
                {{ session('success') }}
            </x-alert-success>

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item link-primary link-offset-2">
                        <a href="{{ route('admin.users.show', $user->id) }}">{{ $user->name }}</a>
                    </li>
                    <li class="breadcrumb-item" aria-current="page">All comments</li>
                </ol>
            </nav>

            <div class="my-6 p-6 bg-white border-b border-gray-200 shadow-sm sm:rounded-lg mt-4">
                @if(count($comments) != 0)
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>Comment text</th>
                            <th></th>
                            <th></th>

                        </tr>
                        </thead>

                        <tbody>
                        @foreach($comments as $comment)
                            <tr>
                                <td class="align-middle w-75" style="text-align: justify">{{ $comment->message }}</td>
                                <td class="align-middle text-body-secondary ">
                                    <small class="text-body-secondary fw-semibold">{{ $comment->updated_at->diffForHumans() }}</small>
                                </td>
                                <td class="align-middle">
                                    <form action="{{ route('admin.comments.delete', $comment) }}" method="post">
                                        <input type="hidden" name="item_id" value="{{ $comment->item_id }}">
                                        @method('delete')
                                        @csrf
                                        <button type="submit" class="btn btn-outline-danger text-gray-700"
                                                onclick="return confirm('Are you sure you wish to delete this user forever !?')">
                                            Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                @else
                    <p class="fs-5">This user haven't written any comments</p>
                @endif
            </div>
        </div>
    </div>
@endsection